name                    = "keycloak"
region                  = "us-east-2"
owner                   = "Roshan Raman Giri"
environment             = "dev"
domain_name             = "keycloak.aawajai.com"
zone_id                 = "Z03028901EPUSX1K65JBK"
container_desired_count = 3
container_port          = 8080
db_instance_class       = "db.t2.micro"
db_port                 = 5432
db_multi_az             = false
db_allocated_storage    = 20
profile                 = "default"